[package]
name = "rust-gui"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rust-gui"
path = "src/main.rs"


[dependencies]
slint = { version = "1.14.1", features = ["unstable-winit-030"] }

[build-dependencies]
slint-build = "1.14.1"

